const AddPropertyConstants = {
  title: "Add Property",
  subtitle: "Fill the form to add a property.",
  buttonContent: "Add Property",
  content: [""],

  inputFields: [
    {
      label: "Name",
      type: "text",
      name: "name",
      placeholder: "Name",
      required: true,
    },
    {
      label: "PropertyType",
      type: "text",
      name: "propertyType",
      placeholder: "PropertyType",
      required: true,
    },
    {
      label: "Number of Bedrooms",
      type: "number",
      name: "bedrooms",
      placeholder: "Number of Bedrooms",
      required: true,
    },
    {
      label: "Number of Beds",
      type: "number",
      name: "beds",
      placeholder: "Number of Beds",
      required: true,
    },
    {
      label: "Number of Bathrooms",
      type: "number",
      name: "bathrooms",
      placeholder: "Number of Bathrooms",
      required: true,
    },
    {
      label: "Price Per Night",
      type: "number",
      name: "pricePerNight",
      placeholder: "Price Per Night",
      required: true,
    },
    {
      label: "Maximum Number of Guests",
      type: "number",
      name: "maxGuests",
      placeholder: "Maximum Number of Guests",
      required: true,
    },
    {
      label: "Address",
      type: "text",
      name: "address",
      placeholder: "Address",
      required: true,
    },
    {
      label: "City",
      type: "text",
      name: "city",
      placeholder: "City",
      required: true,
    },
    {
      label: "zipCode",
      type: "text",
      name: "zipCode",
      placeholder: "zipCode",
      required: true,
    },
    {
      label: "Country",
      type: "text",
      name: "country",
      placeholder: "Country",
      required: true,
    },
    {
      label: "Description",
      type: "text",
      name: "description",
      placeholder: "Description",
      required: true,
    },
    {
      label: "Free Cancelation",
      type: "checkbox",
      name: "freeCancel",
      placeholder: "Free Cancelation",
      required: true,
    },
    {
      label: "Host",
      type: "text",
      name: "host",
      placeholder: "Host",
      required: true,
    },
    {
      label: "Amenities",
      type: "text",
      name: "amenities",
      placeholder: "Amenities",
      required: true,
    },
  ],
};
export default AddPropertyConstants;
